### ISSUE TITLE
jefferson not run

### ISSUE THREAD

**Issue by afby** [sviehb/jefferson#38] opened 2022-03-10 19:30 UTC
Hello
I have a bug, after install, I try jefferson and I have this :

'/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 1.12.1-git20200711.33e2d80-dfsg1-0.6 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/usr/bin/jefferson", line 4, in <module>
    __import__('pkg_resources').run_script('jefferson==0.3', 'jefferson')
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jefferson==0.3' distribution was not found and is required by the application
'

**Comment by qkaiser** [comment] 2022-03-14 08:59
Can you provide more details like the operating system and distribution you use, the exact python version you use and the steps you followed to install jefferson ? This will help us troubleshoot your issue.

**Comment by afby** [comment] 2022-03-18 18:51
Yes, sorry

Linux 5.16.0-kali1-amd64 #1 SMP PREEMPT Debian 5.16.7-2kali1 (2022-02-10) x86_64 GNU/Linux

Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.1
Codename:       kali-rolling

Python 3.9.10

And I followed the README for installation :)

**Comment by qkaiser** [comment] 2022-03-23 16:27
These are the steps I followed on a clean install of kali to get jefferson installed:

```
git clone https://github.com/sviehb/jefferson.git
cd jefferson
sudo apt update
sudo apt install liblzo2-dev python3-pip
sudo python3 -m pip install -r requirements.txt
sudo python3 setup.py install
```

Setup:

```
Linux kali 5.15.0-kali3-amd64 #1 SMP Debian 5.15.15-2kali1 (2022-01-31) x86_64 GNU/Linux
Python 3.9.10 (main, Jan 16 2022, 17:12:18)
RETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.1"
VERSION_ID="2022.1"
VERSION_CODENAME="kali-rolling"
```

I'll edit the installation steps to mention the lzo lib requirements.

**Comment by qkaiser** [comment] 2022-03-23 16:39
Let me know if you get the same bug by following the steps I just provided. Cheers !

**Comment by afby** [comment] 2022-03-26 13:24
Hello, thanks for your reply!
Requirements ok, fresh clone but jefferson not run with same error
But the bug is still there :(

**Comment by qkaiser** [comment] 2022-03-28 07:37
Can you tell me which version of pip you're using ? You can get it this way:

```
python3 -m pip -V
```

**Comment by afby** [comment] 2022-03-29 18:33
pip 22.0.3 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)

**Comment by qkaiser** [comment] 2022-05-13 10:22
Closing as we can't reproduce with clean install of Kali with same OS, distribution, python, and pip version.

**Comment by techdragon** [comment] 2022-06-06 06:23
@QKaiser can you reopen this, as I get the same error trying to install Jefferson to use it with Binwalk on an Ubuntu 20.04.4 virtual machine.

**Comment by techdragon** [comment] 2022-06-06 06:44
@afby can you check the content of the `jefferson` executable. In my case `cat /usr/bin/jefferson` 

For me the content is 
```python
#!/usr/bin/python3
# EASY-INSTALL-SCRIPT: 'jefferson==0.3','jefferson'
__requires__ = 'jefferson==0.3'
__import__('pkg_resources').run_script('jefferson==0.3', 'jefferson')
```

@QKaiser 
During install I get the following output. 
```
/usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
```

I suspect that something is likely to have broken between newer linux distros and the deprecated functionality from `setuptools`. 

---

Update: 

I've managed to work out how to invoke `jefferson` as a workaround but this doesn't explain how to get it to install properly in the first place. It seems as if the default install instructions on Ubuntu 20.04.4 ( and possibly Kali as originally encountered by @afby ) does not install to a location in the `PYTHONPATH`. 

```PYTHONPATH=PYTHONPATH:/usr/lib/python3.8/site-packages/jefferson-0.3-py3.8.egg jefferson``` executes ok for me. But I have not yet gotten to the bottom of what's causing the mismatch between `/usr/lib/python.3.8/` and `/usr/local/lib/python3.8` on Ubuntu 20.04.4

**Comment by qkaiser** [comment] 2022-06-06 15:05
Reopening, will investigate and probably move to a better packaging solution in the near future.

**Comment by afby** [comment] 2022-06-17 16:20
Sorry @techdragon , I changed distribution because of that!
I'm not much help anymore
But thank you for reply!

**Comment by qkaiser** [comment] 2023-01-25 10:10
Clean install on Ubuntu and Kali latest. Probably `PATH` expansion problem due to weird profile files.

**Closed as completed by qkaiser** 2023-01-25 10:10 UTC
Labels: bug

**Comment by Ertavf** [comment] 2023-02-10 16:11
I'm striving to fix the same issue, and I have an easy way to reproduce it.

1. open https://shell.cloud.google.com/?show=ide%2Cterminal
2. [not required] find the three dots left to the your profile picture, select Ephemeral Mode
3. run installation scripts

see mine:
[cloudshell_logs.txt](https://github.com/sviehb/jefferson/files/10709187/cloudshell_logs.txt)

**Comment by qkaiser** [comment] 2023-02-10 16:45
Jefferson is now properly packaged and available from PyPi. You can try installing Jefferson with:

```
python3 -m pip install --user jefferson
```

ONEKEY is now maintaining and supporting Jefferson (as agreed with @sviehb). The most recent developments are happening at https://github.com/onekey-sec/jefferson/. This is where the PyPi packages are built and published from.

**Comment by Ertavf** [comment] 2023-02-10 22:45
I'm grateful for your reply. Installed successfully.

This is the path that led me here:
https://github.com/ReFirmLabs/binwalk/blame/master/INSTALL.md#L62

For those who are new, these two packages need to be installed.
```bash
sudo apt-get install liblzo2-dev
sudo -H pip3 install python-lzo
```
